osx_image: xcode11.3
language: objective-c

script:
- xcodebuild test -enableCodeCoverage YES -workspace Example/MPDebug.xcworkspace -scheme MPDebug-Example -sdk iphonesimulator13.2 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
